apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: 180789647333.dkr.ecr.us-east-1.amazonaws.com/aws-ecr-kubenginx:1.0.0
          resources:
            requests:
              memory: "12Mi"
              cpu: "50m"
            limits:
              memory: "25Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
